### ISSUE TITLE
Allow for YAML configuration

### ISSUE THREAD

**Issue by Zopieux** [facette/facette#98]
While JSON is better than XML, I am not sure it is best suited for configuration files written by humans. The numerous quotes and boring brackets make it easy to do typos.

I suggest allowing for both JSON and YAML configuration files. The example `collectd.json` would look like this in YAML:

```YAML
connector:
  type: rrd
  path: /var/lib/collectd/rrd
  pattern: (?P<source>[^/]+)/(?P<metric>.+).rrd
filters:
- pattern: /
  rewrite: .
  target: metric
- pattern: ^cpu-(\d+)\.cpu-(.+)\.value$
  rewrite: cpu.$1.$2
  target: metric
- pattern: ^df-(.+)\.df_complex-(.+)\.value
  rewrite: df.$1.$2
  target: metric
- pattern: ^disk-(.+)\.disk_(.+)
  rewrite: disk.$1.$2
  target: metric
- pattern: ^entropy\.entropy
  rewrite: entropy
  target: metric
- pattern: ^interface-(.+)\.if_(.+)\.(.+)$
  rewrite: net.$1.$2.$3
  target: metric
- pattern: ^irq.irq-(.+)\.value$
  rewrite: irq.$1
  target: metric
- pattern: ^load\.load
  rewrite: load
  target: metric
- pattern: ^memory\.memory-(.+)\.value$
  rewrite: memory.$1
  target: metric
- pattern: ^processes\.ps_state-(.+)\.value$
  rewrite: proc.state.$1
  target: metric
- pattern: ^processes\.(.+)\.value$
  rewrite: proc.$1
  target: metric
- pattern: ^swap\.swap-(.+)\.value$
  rewrite: swap.$1
  target: metric
- pattern: ^swap\.swap_io-(.+)\.value$
  rewrite: swap.io.$1
  target: metric
- pattern: ^users\.users\.value
  rewrite: users.count
  target: metric
```
Sorry for the lack of syntax highlighting, seems Github doesn't do it for this language.
